name: PHP CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        coverage: none
        extensions: mbstring, dom, simplexml

    - name: Cache Composer packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.composer/cache/files
          vendor
        key: ${{ runner.os }}-php-8.4-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.4-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Run PHPUnit
      run: vendor/bin/phpunit

    - name: Run Psalm
      run: vendor/bin/psalm
